{% set version = "5.2.0" %}

package:
  name: chardet
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/chardet/chardet-{{ version }}.tar.gz
  sha256: 1b3b6ff479a8c414bc3fa2c0852995695c4a026dcd6d0633b2dd092ca39c1cf7

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vvv
  entry_points:
    - chardetect = chardet.cli.chardetect:main

requirements:
  host:
    - python {{ python_min }}.*
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - chardet
  commands:
    - chardetect --help

about:
  home: https://github.com/chardet/chardet
  license: LGPL-2.1-only
  license_family: GPL
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    chardet is a character encoding auto-detector in Python.
  doc_url: http://chardet.readthedocs.org/
  doc_source_url: https://github.com/chardet/chardet/blob/master/docs/index.rst
  dev_url: https://github.com/chardet/chardet


extra:
  recipe-maintainers:
    - dan-blanchard
    - sigmavirus24
    - nehaljwani
