{% set version = "7.1.0" %}

package:
  name: chardet
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/chardet/chardet-{{ version }}.tar.gz
  sha256: 8f47bc4accac17bd9accbb4acc1d563acc024a783806c0a43c3a583f5285690b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv
  entry_points:
    - chardetect = chardet.cli:main

requirements:
  host:
    - hatchling
    - hatch-vcs
    - python {{ python_min }}.*
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - chardet
  commands:
    - chardetect --help

about:
  home: https://github.com/chardet/chardet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    chardet is a character encoding auto-detector in Python.
  doc_url: http://chardet.readthedocs.org/
  doc_source_url: https://github.com/chardet/chardet/blob/main/docs/index.rst
  dev_url: https://github.com/chardet/chardet


extra:
  recipe-maintainers:
    - dan-blanchard
    - sigmavirus24
    - nehaljwani
