schema_version: 1

context:
  version: "7.4.3"

package:
  name: chardet
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/chardet/chardet-${{ version }}.tar.gz
  sha256: cc1d4eb92a4ec1c2df3b490836ffa46922e599d34ce0bb75cf41fd2bf6303d56

build:
  noarch: python
  number: 0
  script: ${{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation
  python:
    entry_points:
      - chardetect = chardet.cli:main

requirements:
  host:
    - hatchling
    - hatch-vcs
    - python ${{ python_min }}.*
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - chardet
      pip_check: true
  - script:
      - chardetect --help

about:
  homepage: https://github.com/chardet/chardet
  license: 0BSD
  license_file: LICENSE
  summary: Universal character encoding detector
  description: |
    chardet is a character encoding auto-detector in Python.
  documentation: http://chardet.readthedocs.org/
  repository: https://github.com/chardet/chardet

extra:
  recipe-maintainers:
    - jschueller
    - dan-blanchard
    - sigmavirus24
    - nehaljwani